---
- name: install updates (CentOS)
  tags: always,update
  dnf:
    update_only: yes
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: install updates (Ubuntu)
  tags: always,update
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
